name: Creator360 Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/creator360:$IMAGE_TAG .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/creator360:$IMAGE_TAG

  deploy-to-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name creator360-unifiedsaas-web \
            --resource-group Creator360-UnifiedSaaS-RG \
            --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/creator360:$IMAGE_TAG \
            --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }}

      - name: Restart Azure Web App
        run: az webapp restart --name creator360-unifiedsaas-web --resource-group Creator360-UnifiedSaaS-RG

      - name: Check Deployment Status
        run: az webapp show --name creator360-unifiedsaas-web --resource-group Creator360-UnifiedSaaS-RG
